services:
  accounts:
    image: pavelboldienkov/accounts:1.0
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - banking
  loans:
    image: pavelboldienkov/loans:1.0
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - banking
  cards:
    image: pavelboldienkov/cards:1.0
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - banking
networks:
  banking:
    driver: "bridge"
