spring:
  application:
    name: "configserver"
  profiles:
    #    active: native
    active: git
  cloud:
    config:
      server:
#        native:
        #          search-locations: "classpath:/config"
        git:
          uri: https://github.com/paul566576/banking-config.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "SB02Aai1fUArveqvMkMrvk2JS7eRSjTT"

server:
  port: 8071
